- name: Ensure a job that runs every 2 minuets. Appends the current date and time to the file /tmp/logme.txt.
  hosts: devops
  become: yes
  
  
  tasks:
  
  - name: Verifies that cronie is installed in the system.
    ansible.builtin.package:
      name: cronie
      state: present

  - name: Verifies that cronie is running.
    ansible.builtin.service:
      name: crond
      state: started
      enabled: yes


  - name: Verifies that /tmp/logme.txt file exists.
    ansible.builtin.file:
      path: /tmp/logme.txt
      state: touch
      owner: root
      group: root
      mode: '0777'

  - name: creating the job
    ansible.builtin.cron:
      name: "adds timestamp to /tmp/logme.txt"
      minute: "*/2"
      job: "echo $(date '+%Y-%m-%d %H:%M:%S') >> /tmp/logme.txt"
