---
- name: Install common packages on all nodes
  hosts: devops
  tasks:
    - name: Install httpd and firewalld packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
        - httpd
        - firewalld

    - name: Ensure httpd and firewalld services is started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

          #    - name: Install firewalld package
          #     ansible.builtin.package:
          # name: firewalld
          # state: latest

          #- name: Ensure firewalld service is started and enabled
          # ansible.builtin.service:
          #name: firewalld
          #state: started
          #enable: yes
   
    - name: permit traffic in default zone for http and https services
      ansible.posix.firewalld:
        service: http, https
        permanent: true
        state: enabled

    - name: permit traffic in default zone for http and https services
      ansible.posix.firewalld:
        service: http, https
        permanent: true
        state: enabled

