- name: verify kubernetes python library is installed
  ansible.builtin.pip:
    name: kubernetes
    state: latest
  tags: always



- name: Check if JFrog is installed in Kubernetes cluster
  command: kubectl get pods -n artifactory -l app=artifactory
  register: jfrog_pods
  ignore_errors: true
  tags:
    - always


- name: Installation will be skipped
  debug:
    msg: "Installation will be skipped, the version jfrog is already running in the cluster!"
  when: jfrog_pods.stdout_lines | length > 0
  tags:
    - always
